# Generated by Django 4.1.6 on 2023-02-06 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='name',
            new_name='board_name',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='user',
            new_name='board_user',
        ),
        migrations.AddField(
            model_name='board',
            name='board_created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
