# Generated by Django 4.1.6 on 2023-02-06 20:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Board', '0002_rename_name_board_board_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_description', models.CharField(max_length=500)),
                ('ticket_title', models.CharField(max_length=500)),
                ('ticket_duedate', models.DateField(default=datetime.date.today)),
                ('ticket_prio', models.CharField(max_length=500)),
                ('ticket_category', models.CharField(max_length=500)),
                ('ticket_created_at', models.DateField(default=datetime.date.today)),
                ('ticket_board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_in_board', to='Board.board')),
            ],
        ),
        migrations.CreateModel(
            name='ticketToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t2u_created_at', models.DateField(default=datetime.date.today)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_user',
            field=models.ManyToManyField(through='Board.ticketToUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='boardToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b2u_created_at', models.DateField(default=datetime.date.today)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='board_to_user',
            field=models.ManyToManyField(through='Board.boardToUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
