# Generated by Django 4.1.6 on 2023-02-07 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Board', '0003_ticket_tickettouser_ticket_ticket_user_boardtouser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_to_user',
            field=models.ManyToManyField(through='Board.TicketToUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_to_user',
            field=models.ManyToManyField(through='Board.BoardToUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
