# Generated by Django 4.1.6 on 2023-02-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0004_remove_ticket_ticket_user_ticket_ticket_to_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='boardtouser',
            name='board',
        ),
        migrations.RemoveField(
            model_name='boardtouser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_board',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_category',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='boardToUser',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_in_list', to='Board.list'),
        ),
    ]
