# Generated by Django 4.1.6 on 2023-02-10 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Board', '0005_list_remove_boardtouser_board_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_to_user',
            field=models.ManyToManyField(through='Board.TicketToUser', to='Board.userprofile'),
        ),
        migrations.AlterField(
            model_name='tickettouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.userprofile'),
        ),
    ]
