# Generated by Django 4.1.6 on 2023-02-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0007_alter_ticket_ticket_to_user_alter_tickettouser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
