# Generated by Django 4.1.6 on 2023-02-10 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Board', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_to_user',
            field=models.ManyToManyField(related_name='ticket_to_user', through='Board.TicketToUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
